# Generated by Django 2.2.5 on 2019-12-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_brand', models.CharField(choices=[('Hiper X', 'Hiper X')], max_length=25)),
                ('ram_size', models.PositiveIntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64')])),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_board', models.CharField(choices=[('Asus Prime', 'Asus Prime'), ('Gigabyte', 'Gigabyte'), ('ASRock Fatal', 'ASRock Fatal')], max_length=25)),
                ('processor', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD'), ('Ambos', 'Ambos')], max_length=25)),
                ('ram_slots', models.PositiveIntegerField(choices=[(2, '2'), (4, '4')])),
                ('ram_max_size', models.PositiveIntegerField(choices=[(16, '16'), (64, '64')])),
                ('has_integrated_video', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(choices=[('Intel Core i5', 'Intel Core i5'), ('Intel Core i7', 'Intel Core i7'), ('AMD Athlon', 'AMD Athlon'), ('AMD Ryzen 7', 'AMD Ryzen 7')], max_length=50)),
                ('processor_brand', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VideoBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_board', models.CharField(choices=[('Gigabyte Geforce GTX 1060 6GB', 'Gigabyte Geforce GTX 1060 6GB'), ('PNY RTX 2060 6GB', 'PNY RTX 2060 6GB'), ('Radeon RX 580 8GB', 'Radeon RX 580 8GB')], max_length=100)),
            ],
        ),
    ]
