# Generated by Django 2.2.5 on 2019-12-10 03:40

from django.db import migrations


def seed_processors(apps, schema_editors):

    Processor = apps.get_model('api', 'processor')
    [
        Processor(
            processor="Intel Core i5", processor_brand="Intel"
        ).save(),
        Processor(
            processor="Intel Core i7", processor_brand="Intel"
        ).save(),
        Processor(
            processor="AMD Ryzen 7", processor_brand="AMD"
        ).save(),
        Processor(
            processor="AMD Athlon", processor_brand="AMD"
        ).save()
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_processors)
    ]
