# Generated by Django 2.2.5 on 2019-12-10 03:44

from django.db import migrations


def seed_memory(apps, schema_editor):

    Memory = apps.get_model('api', 'Memory')

    [
        Memory(
            ram_brand="Hiper X", ram_size=4
        ).save(),
        Memory(
            ram_brand="Hiper X", ram_size=8
        ).save(),
        Memory(
            ram_brand="Hiper X", ram_size=16
        ).save(),
        Memory(
            ram_brand="Hiper X", ram_size=32
        ).save(),
        Memory(
            ram_brand="Hiper X", ram_size=64
        ).save(),

    ]


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191210_0340'),
    ]

    operations = [
        migrations.RunPython(seed_memory)
    ]
