# Generated by Django 2.2.5 on 2019-12-10 03:44

from django.db import migrations


def seed_Video_Board(apps, schema_editor):

    Video_Board = apps.get_model('api', 'VideoBoard')

    [
        Video_Board(video_board='Gigabyte Geforce GTX 1060 6GB').save(),
        Video_Board(video_board='PNY RTX 2060 6GB').save(),
        Video_Board(video_board='Radeon RX 580 8GB').save(),

    ]


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191210_0344'),
    ]

    operations = [
        migrations.RunPython(seed_Video_Board)
    ]
