# Generated by Django 2.2.5 on 2019-12-10 03:44

from django.db import migrations

def seed_mother_board(apps, schema_editor):
    
    MotherBoard = apps.get_model('api', 'MotherBoard')  
    [
        MotherBoard(mother_board='Asus Prime', processor='Intel', ram_slots=2, ram_max_size=16, has_integrated_video=False).save(),
        MotherBoard(mother_board='Gigabyte', processor='AMD', ram_slots=2, ram_max_size=16, has_integrated_video=False).save(),
        MotherBoard(mother_board='ASRock Fatal', processor='Ambos', ram_slots=4, ram_max_size=64, has_integrated_video=True).save()

    ] 


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191210_0344'),
    ]

    operations = [
        migrations.RunPython(seed_mother_board)
    ]
