# Generated by Django 2.2.5 on 2019-12-10 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20191210_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_id', models.ManyToManyField(to='api.Memory')),
                ('mother_board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MotherBoard')),
                ('processor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Processor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_board_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.VideoBoard')),
            ],
        ),
    ]
